### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by iammalikkhalil** [muhammadrao1246/JAVA-OOP-COURSE#1]
**bro error a rha hy kh aap ny jo variables bnaya hain woh use kahin nii kea or last wali class jb public hy to new file bna kr wahn likhoo......**

@muhammadrao1246 reply plz
![image](https://user-images.githubusercontent.com/112185928/203692691-b1a03e61-7845-405a-8571-e547e4894503.png)

**Comment by muhammadrao1246** [comment]
Yr wo variables ka use na hona yeh sirf warning hai farq nai prta baqi yeh program bnaya chalnay k liye nai balkay yeh btanay k liye hai k kin datatypes ko kis trhan say hum kisi aur datatype main convert kr skte

**Comment by iammalikkhalil** [comment]
thankuu bro!!
your answer helps me a lot

**Comment by muhammadrao1246** [comment]
> thankuu bro!! your answer helps me a lot

My pleasure 🥰
